// Game Variables
var score = 0;
var time = 60;
var level = 1;
var intervalId;
var timeoutIds = [];
var gameStarted = false;
var redclicks = 0;
var greenclicks = 0;
var genGreen = 0;
var genRed = 0;
var highScore = 0;
var percentage = 0;

// const click = document.getElementById('click');
// const tikTikSound = document.getElementById('tikTikSound');
// const gameOver = document.getElementById('gameOver');

// Game Levels
var levels = [
  {
    numSquares: 60,
    interval: 1000,
    colors: ["green", "red"],
  }
];

// Game Functions
function startGame() {
  gameStarted = true;
  time = 60;
  score = 0;
  genGreen = 0;
  genRed = 0;
  redclicks = 0;
  greenclicks = 0;
  percentage = 0;
  intervalId = setInterval(countdown, 1000);
  spawnSquares();
}

function countdown() {
  if (time == 0) {
    endGame();
    return;
  }
  time--;
  $("#time").text(time);
  // if(time==11) {
  //   tikTikSound.play();
  // }
}

function spawnSquares() {
  for (var i = 0; i < levels[level - 1].numSquares; i++) {
    var timeoutId = setTimeout(spawnSquare, i * levels[level - 1].interval);
    timeoutIds.push(timeoutId);
  }
}

function spawnSquare() {

  var existingShapes = [];
  var shapes = ["square", "hex", "circle"];
  var shape = shapes[Math.floor(Math.random() * shapes.length)];
  var color = levels[level - 1].colors[Math.floor(Math.random() * levels[level - 1].colors.length)];
  var size = 80;
  var x = Math.floor(Math.random() * ($("#game").width() - size) - 10);
  var y = Math.floor(Math.random() * ($("#game").height() - size) - 10);
  var $shape;

  switch (shape) {
    case "square":
      $shape = $("<div class='square'></div>");
      break;
    case "hex":
      $shape = $("<div class='hex'></div>");
      break;
    case "circle":
      $shape = $("<div class='circle'></div>");
      break;
  }

  $shape.css(
    {
      "background-color": color,
      "border-color": color,
      "left": x,
      "top": y
    });

  // counting the colour wise shape generated by code
  if($shape.css("background-color") === "red") {
    genRed++;
  }
  else {
    genGreen++;
  }

  // to avoid overlappping 
  var overlapsExistingShape = true;
  while (overlapsExistingShape) {
    overlapsExistingShape = false;
    for (var i = 0; i < existingShapes.length; i++) {
      var existingShape = existingShapes[i];
      if (x + size > existingShape.x && x < existingShape.x + existingShape.size &&
        y + size > existingShape.y && y < existingShape.y + existingShape.size) {
        overlapsExistingShape = true;
        x = Math.floor(Math.random() * ($("#game").width() - size) - 10);
        y = Math.floor(Math.random() * ($("#game").height() - size) - 10);
        $shape.css({
          "left": x,
          "top": y
        });
        break;
      }
    }
  }

  // click function
  $shape.click(function() {

    if ($(this).css("background-color") == "rgb(255, 0, 0)") {
      redclicks++;
    } else {
      greenclicks++;
    }
    score = greenclicks - redclicks;

    // high score storation
    if (highScore < score) {
      highScore = score;
      storeHighscore();
    }
    $("#high-score").text(highScore);
    $("#score").text(score);
    $(this).fadeOut(200);
  });
  $("#game").append($shape);
  setTimeout(function() {
    $shape.fadeOut(200);
  }, 1000);

  // store current position
  existingShapes.push({
    "x": x,
    "y": y,
    "size": size
  });

}

//function to store highScore
function storeHighscore() {
  localStorage.setItem("highScore", highScore);
}


// function for End game
function endGame() {

  // tikTikSound.pause(); // Pause the tik tik sound
  // gameOver.play();
  // tikTikSound.currentTime = 0; // Reset the sound to the beginning

  percentage = greenclicks/genGreen * 100;
  percentage = parseFloat(percentage);
  clearInterval(intervalId);
  gameStarted = false;

  $("#level-buttons button").css('background', '#81adee');

  for (var i = 0; i < timeoutIds.length; i++) {
    clearTimeout(timeoutIds[i]); // use the stored IDs to clear the timeouts
  }

  $("#game").empty();
  var $scorecard = generateScorecard();
  $("#game").append($scorecard);
}

// reset Game
function resetGame() {
  // Stop game and clear timeouts
  clearInterval(intervalId);

  for (var i = 0; i < timeoutIds.length; i++) {
    clearTimeout(timeoutIds[i]);
  }

  // Reset game variables and UI
  gameStarted = false;
  redclicks = 0;
  greenclicks = 0;
  genRed = 0;
  genGreen = 0;
  score = 0;
  time = 60;
  level = 0;
  timeoutIds = [];
  $("#score").text(score);
  $("#time").text(time);
  $("#game").empty();

  // Reset level buttons
  $("#level-buttons button").css('background', '#81adee');
}


// Game Setup
$(document).ready(function() {

  // load the high score from local storage
  if (localStorage.getItem("highScore")) {
    highScore = parseInt(localStorage.getItem("highScore"));
  }

  // reset button
  $("#reset").click(function() {
    resetGame();
  });

  $("#level1").click(function() {
    if (gameStarted) return;
    else {
      resetGame();
      $("#level1").css('background', '#43e555');
      level = 1;
      startGame();
    }
  });
});

// Reset game on page load
$(window).on("load", function() {
  resetGame();
});



function generateScorecard() {
  
  // Retrieve the name from localStorage
  var name = localStorage.getItem("name");  
  var $scorecard = $("<div class='scorecard'></div>");
  var $scoreDetails = $("<div class='score-details'></div>");

  $scoreDetails.append("<p id='displayText' >Player Name: " + name + "</p></br>");
  $scoreDetails.append("<p id='tgreen' class='tscore'>Total Green shape genrated: " + genGreen + "</p>");
  $scoreDetails.append("<p id='tred' class='tscore'>Total Red shape genrated: " + genRed + "</p></br>");
  $scoreDetails.append("<p id='green' class='mscore'>Green clicks: " + greenclicks + "</p>");
  $scoreDetails.append("<p id='red' class='mscore'>Red clicks: " + redclicks + "</p></br>");
  $scoreDetails.append("<p id='final' class='mscore'>Final score: " + score + "</p>");
  $scoreDetails.append("<p id='percent' class='mscore'> Percentage Score is: " + percentage.toFixed(2) + "%</p></br>");

  var $downloadButton = $("<button id='download'>Download Scorecard</button>");
  $downloadButton.click(downloadScorecard);

  $scorecard.append($scoreDetails);
  $scorecard.append($downloadButton);

  return $scorecard;
}

function downloadScorecard() {

  var name = localStorage.getItem("name");
  var csvContent = "data:text/csv;charset=utf-8,";
  csvContent += "Name,Generated Green,Green clicks,Generated Red,Red clicks,Final Score,%\n";
  csvContent += name + "," + genGreen +","+ greenclicks + "," + genRed + "," + redclicks +","+ score +","+ percentage + "\n";

  var encodedUri = encodeURI(csvContent);
  var link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", name + "-Decision.csv");
  document.body.appendChild(link);

  link.click();
}
